### ISSUE TITLE
Modrinth incorrect supported version

### ISSUE THREAD

**Issue by ASUT0R0** [SamStone1000/MAE2#1]
In Modrinth (not in Curseforge) MAE2 page shows 1.20.1-1.20.6 Forge (and also Neoforge in 1.1.0) is supported.
But AE2 has dropped Forge (and Fabric) support and only supports Neoforge as of 1.20.2, also Neoforge is no longer compatible with Forge as of 1.20.2 and not load Forge mod.

Currently All released MAE2 is built for Forge, which means it won't be loaded in 1.20.2-1.20.6. So supported version Modrinth page is incorrect, should be fixed.

**Comment by SamStone1000** [comment]
Yeah I knew it was probably incompatible with newer versions, but didn't want to mark them as such until I was sure it wouldn't work. I was planning on checking version compatibility at some point and kept putting it off. It looks like 1.20.1 is the only version it can currently work on, so I'll mark it as such on Modrinth. 

If you wanted MAE2 on 1.20.6, I can try and see how hard it would be to port. I'm mainly making this mod for Monifactory which is on 1.20.1, but hopefully MAE2 is simple enough that porting would just be renaming forge to neoforge.
